### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#1]
In 2016 I started prototyping a distributed OCR system ("docr"):

* [docr-blob](https://github.com/kba/docr-blob): File storage
* [docr-common](https://github.com/kba/docr-common): Common functionality and JSON schemas for tasks and configurations
* [docr-jobserver](https://github.com/kba/docr-jobserver): Server accepting jobs and distributing them via a task queue
* [docr-worker](https://github.com/kba/docr-worker):  Worker component executing tasks provided by the jobserver, to be run on commodity hardware

Plus some Dockerfiles for containerizing job server and workers. It isn't usable code and quite abandoned but might serve as an inspiration for architecture, configuration etc.

**Comment by cneud** [comment]
Excellent inspiration! Will close though as the project architecture is now defined according to [v1.0.0](https://github.com/OCR-D/spec/releases/tag/v1.0.0).
