### ISSUE TITLE
Koordinaten innerhalb von PAGE XML

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/spec#10]
Es ist nicht klar, dass sich die PAGE XML Daten immer auf das OriginalBild beziehen müssen.

Ok, bei Cropping ist die Umrechnung einfach 

Hier fehlt aber das 'AlternativeImage' falls das Bild tatsächlich beschnitten und nicht nur der Suchbereich eingeschränkt werden soll.

Bei deskewing wird es schon schwieriger. Wer macht die Umrechnung? Machen das die Modulprojekte? Dann müssen die Schnittstellen genau definiert sein:
Beispiel:
```
comment="deskewed" skew="1.67" rotation="normal"
```
Was ist normal?
Was mache ich wenn bei comment ein Eintrag steht den ich nicht kenne!? (Gedreht, deskewing, ...)
Was bedeutet 1.67? (Grad oder Radiant?)
Es fehlt die Information um welchen Punkt es gedreht wurde!? Um die Bildmitte? Um die Bildmitte des 'beschnittenen' Bildes? Das ist für die Rückrechnung der Koordinaten aber essentiell.

In diesem Fall mag es irgendwie dokumentierbar sein. Bei anderen Methoden wird es eventuell schwieriger.

Bei Normalisierung schreibst du nur `comment="B/W"`. 

zu `B/W`: Hier gibt es auf jeden Fall bereits standardisierte Begriffe, die man dann verwenden sollte.

Ist es das Originalbild in SW?
Oder wurde das Bild zuvor gedreht?
Oder gar beschnitten?
Wenn ja, in welcher Reihenfolge!?

--> Das können die Modulprojekte nicht leisten, da ja nachträglich neue Methoden dazukommen können.

Dann wäre das das Problem des Workflows. Das macht es aber nicht
viel besser. Wir wissen zwar genau was ein Modul macht und in welcher Reihenfolge die Optimierungen aufgerufen wurden. Allerdings müssen wir dann immer sicherstellen auf welches Bild sich die in Page XML gespeicherten Daten beziehen. Wenn die das beschnittene gedrehte binarisierte Bild nehmen und dessen Koordinaten in PAGE XML schreiben dann müssen wir das wissen. Ein anderes Modul benutzt eventuell direkt das Originalbild. Also da muss sehr genau dokumentiert werden sonst landest du direkt in der Hölle.

Wenn jeder nur ein Bild bekommt wissen wir genau was der Bezugspunkt ist. Dann ist das mit dem METS aber nur ein Container mit einem Teil aller Informationen.
Der Workflow muss also immer alle 'unnötigen' Informationen vorher entfernen.

**Comment by cneud** [comment]
> Es ist nicht klar, dass sich die PAGE XML Daten immer auf das OriginalBild beziehen müssen. 
Ok, bei Cropping ist die Umrechnung einfach
Bei deskewing wird es schon schwieriger. Wer macht die Umrechnung? Machen das die Modulprojekte? Dann müssen die Schnittstellen genau definiert sein:
Beispiel:
> comment="deskewed" skew="1.67" rotation="normal"
Was ist normal?
Was mache ich wenn bei comment ein Eintrag steht den ich nicht kenne!? (Gedreht, deskewing, ...)
Was bedeutet 1.67? (Grad oder Radiant?)
Es fehlt die Information um welchen Punkt es gedreht wurde!? Um die Bildmitte? Um die Bildmitte des 'beschnittenen' Bildes? Das ist für die Rückrechnung der Koordinaten aber essentiell.
In diesem Fall mag es irgendwie dokumentierbar sein. Bei anderen Methoden wird es eventuell schwieriger.
Bei Normalisierung schreibst du nur comment="B/W".
zu B/W: Hier gibt es auf jeden Fall bereits standardisierte Begriffe, die man dann verwenden sollte.
Ist es das Originalbild in SW?
Oder wurde das Bild zuvor gedreht?
Oder gar beschnitten?
Wenn ja, in welcher Reihenfolge!?

Bezug wird immer über `mets:fileGrp` Attribut `USE` sichergestellt.

> Hier fehlt aber das 'AlternativeImage' falls das Bild tatsächlich beschnitten und nicht nur der Suchbereich eingeschränkt werden soll.

Stattdessen wird das `USE` Attribut `OCR-D-IMG-CROP` verwendet. Bei Verwendung von 'AlternativeImage' innerhalb von PAGE, [muss dies auch im METS dokumentiert werden](https://ocr-d.github.io/mets#if-in-page-then-in-mets).
