### ISSUE TITLE
What is a MP?

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/spec#111]
One of the first things I read at https://ocr-d.github.io is:

> Command line tools provided by MP

However, the site does not define "MP", nor does the [glossary](https://ocr-d.github.io/glossary).

**Comment by cneud** [comment]
MP = (OCR-D) Module Project, cf. https://ocr-d.github.io/projects. Will leave this open until we explain this either in the first mention or glossary

**Comment by mikegerber** [comment]
Almost the same for METS and PAGE, but these are at least things known outside of OCR-D :) I do think they should have an entry in the glossary, though. Also, the [PAGE conventions page](https://ocr-d.github.io/page) should link to "the PAGE XML standard" (the METS conventions page already does link to upstream METS).

**Comment by kba** [comment]
Fixed in https://github.com/OCR-D/spec/commit/017313d34ab9a399f436d2b59fd2b691d0d1d055
