### ISSUE TITLE
Define printspace and border for the glossary

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#114]
We use PrintSpace not in the typographical sense but border-cropped including margin notes, page numbers etc.

**Comment by wrznr** [comment]
Maybe @cthomasdta and @susannehaaf would also be interested in that issue.

**Comment by wrznr** [comment]
@kba This is somewhat outdated since we do not use `PrintSpace` for cropping any longer (but `Border` as it is intended), right?

**Comment by kba** [comment]
Right. Would still be good to define those terms.
