### ISSUE TITLE
Tools should implement --help

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#115]
c.f. https://github.com/OCR-D/ocrd_tesserocr/issues/47

Help should be `"description"` field from ocrd-tool.json

**Comment by EEngl52** [comment]
@kba can this be closed?

**Comment by cneud** [comment]
With f6e357853ecf0c6194cecee32855525da90c8b4e, I think this can be released next week

**Comment by kba** [comment]
Was already released with [v3.5.0](https://github.com/OCR-D/spec/releases/tag/v3.5.0)
