### ISSUE TITLE
Unique identifier from METS

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#15]
ISIL (`mods:physicalLocation`) + PPN?

Custom `source` on `mods:recordIdentifier`?

Was tun bei mehreren PPN?

c.f. https://github.com/OCR-D/spec/pull/14/files#diff-e71131d1fca979232262d6b30a01e067

**Comment by kba** [comment]
@cneud 

ISIL + PPN not feasible because not all orgs have ISIL and PPN for series and work not distinguishable.

Alternative: Use identifer from `mods:identifier[@type="purl"]` which is mandatory and unique.

**Comment by cneud** [comment]
A combination of `mods:identifier[@type="purl"]` with `DMDLOG` is unique, available for all DFG-funded (DFG-Viewer compatible) METS files and allows referencing items on page level.

**Comment by cneud** [comment]
Fixed by 915e006540262ea7702cc98d9497b84534fcd4ec
