### ISSUE TITLE
Add JSON-LD to WebAPI

### ISSUE THREAD

**Issue by mweidling** [OCR-D/spec#194]
Resources should follow the [JSON-LD](https://json-ld.org/) convention of assigning the resource URL as @id attribute.

Document JSON-LD convention for `@id`.

See #173.

**Comment by krvoigt** [comment]
@mweidling Is this also part of the reference implementation?

**Comment by mweidling** [comment]
No, we want to implement/add it to the API in general, but it's not essential. That's why we postponed it.

**Comment by kba** [comment]
> No, we want to implement/add it to the API in general, but it's not essential. That's why we postponed it.

The `Resource` schema definition contains `@id` for the URL, that is in the draft already. And frankly, that is the only feature I really think is important for the Web API. I don't think we need full JSON-LD with `@context` and semantic mapping of property names etc. for such a limited and pragmatic API.
