### ISSUE TITLE
Add Docu about Changes/Upgrades to our tech stack

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/spec#213]
Add information to decision log and link it to further more detailed documentation:

[Changes/Upgrades to our tech stack](https://pad.gwdg.de/zVTkp0B0TOy8FCxkPVHvTg#):
** supported python versions
** linux base image
** additional libraries/software (MongoDB, uvicorn...) (

**Comment by lena-hinrichsen** [comment]
added this to https://ocr-d.de/en/decisions a while ago 👍
