### ISSUE TITLE
USE attribute values for Ground Truth

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#32]
In 1.2 the list of attribute values for `fileGrp/@USE` is missing attributes for ground truth, such as (just the format)

* `OCR-D-GT-PAGE`
* `OCR-D-GT-ALTO`
* `OCR-D-GT-HOCR`

Alternatively, use the same syntactical conventions as for OLR/OCR results:

* `OCR-D-GT-SEG-LINE`
* `OCR-D-GT-IMG-BIN`

@cneud @VolkerHartmann

**Comment by cneud** [comment]
There was a preliminary convention similar to option (1), but this was never fully thought through. While it will be more clumsy and complex, my view is that we should take option (2) - but limit to as few cases as really required. In practice, we already have assembled (and distributed) ground truth with varying degrees of content, at least these kinds: only layout structures with no text, text+coordinates, text without coordinates and possibly we might do purely image-based ground truth as well (for e.g. cropping or deskewing).

Based on that I would opt for following similar conventions as we do for OCR/OLR results.

**Comment by kba** [comment]
For the GT distributed by OCR-D, we could note this in and/or generate METS from https://docs.google.com/spreadsheets/d/1PR6M4-aQhC3V7-_gd03sjK6I89phK6ouXhwXqxek0Zw

**Comment by kba** [comment]
@tboenig

**Comment by VolkerHartmann** [comment]
Indeed: For checking the results of the module projects it would be helpful to have a GT file for each step, but it could also be generated from the complete GT file via 'filter' .
Only information is added and no existing ones change, right?(Is it the same for hOCR and ALTO?)
If this is the case, it is actually enough to have only one PAGE file. 
If not we should prefer the second option.
