### ISSUE TITLE
Page/block segmentation underspecified

### ISSUE THREAD

**Issue by cneud** [OCR-D/spec#38]
The current [spec](https://ocr-d.github.io/mets#file-group-id-syntax) for the `fileGrp`s is not sufficiently clear in the distinction/explanation of the concepts used in `<mets:fileGrp USE=”OCR-D-SEG-PAGE”>`, `<mets:fileGrp USE=”OCR-D-SEG-BLOCK”>` and other commonly used terms in the field such as e.g. `region`. 

We should also keep in mind that there can be segmentation steps that lie only in the classification of text vs. non-text regions (imho anyOCR does that), or in the classification of various classes of non-textual elements (tables, images etc.).

**Comment by kba** [comment]
We should really have a glossary to define the terms as we use them in the specs and reference implementation, as part of the specs.

**Comment by kba** [comment]
Collecting glossary terms now here https://github.com/OCR-D/spec/wiki/Glossary

**Comment by cneud** [comment]
Clarified now in the [glossary](https://ocr-d.github.io/glossary#layout-and-typography).
