### ISSUE TITLE
AlternativeImage "comments" attribute for grayscale images

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#41]
Such as ocropus' `nrm`. For other transformations we use the form `binarized`, `dewarped` etc (c.f. #29). How do we name alternative images that are kind-of-binarized but with some gray at the edges of glyphs?

**Comment by wrznr** [comment]
I have to check the idea and the "techniques" of this image transformation process. But given the file extension, I opt for `normalized` (with further explanations in the glossary).

**Comment by kba** [comment]
The reasoning why ocropy does it like this is explained in the [ocropy wiki](https://github.com/tmbdev/ocropy/wiki/FAQ#when-can-colorful-grayscale-or-black-and-white-images-used).

`normalized` makes sense esp. considering the `nrm` suffix but is a very generic term. `semi-binarized`? `grayscalized`? `quasi-binarized`?

**Comment by wrznr** [comment]
`grayscalized` is technically not correct, right? What about `ternarized`?

**Comment by wrznr** [comment]
It will be `grayscale_normalized`.

**Comment by kba** [comment]
OK, so `grayscale_normalized` for `comments` of the resulting mets:file. Should we also extend the `step` property in `ocrd-tool.json` to contain `preprocessing/optimization/grayscale_normalization` in addition to `preprocessing/optimization/binarization`?

**Comment by wrznr** [comment]
Yes!

**Comment by kba** [comment]
Is in v1.1.5, both the docs and schema.
