### ISSUE TITLE
Update automation mechanism for MP software

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#51]
@VolkerHartmann 

https://github.com/OCR-D/spec/issues/30#issuecomment-384868281

> 'Tools MUST be described in a file ocrd_tool.json in the root of the repository.'
> In my opinion we 'only' have to register the URL of the repository and if there are any changes
we must have the possibility to rescan the repo and/or to version the algorithm by its hash (I think tag may not enough)

**Comment by kba** [comment]
@VolkerHartmann Make `version` part of the ocrd-tool.json? Wouldn't that accomplish what you want? Rescanning will trigger update if version changed.

**Comment by VolkerHartmann** [comment]
Perfect! By supporting the version number in ocrd-tool.json we can handle things automatically.
