### ISSUE TITLE
Extend list of processing steps.

### ISSUE THREAD

**Issue by wrznr** [OCR-D/spec#64]
We need at least `recognition/post-correction` but most probably many others as well.

**Comment by cneud** [comment]
You mean for the `<mets:fileGrp USE>`? We do already have a very simple `<mets:fileGrp USE="OCR-D-COR-CIS">` and `<mets:fileGrp USE="OCR-D-COR-ASV">` for the post-correction methods of CIS-LMU and ASV respectively, but probably more/other (generic) post-correction steps should be covered too? What *many* others would you imagine (e.g. post-correction of structural markup etc.)?

**Comment by wrznr** [comment]
No. I refer to the representation of the use attributes within `ocrd-tool.json`.

**Comment by kba** [comment]
Or `postprocessing/alignment' or `postprocessing/voting`?

**Comment by VolkerHartmann** [comment]
Feel free to add additional processing steps.
On the other hand we should avoid defining too many terms, because otherwise the categorization is too fine-granular.

**Comment by wrznr** [comment]
@wrznr Push.
