### ISSUE TITLE
Page-XML mimetype

### ISSUE THREAD

**Issue by finkf** [OCR-D/spec#65]
In der Dokumentation sollte der mimetype von Page-XML an prominenter Stelle aufgefuehrt sein.

**Comment by kba** [comment]
https://github.com/OCR-D/spec/commit/477d101690db8a4d3d0c681c311486051ec50956 introduced this after discussion in #33, so is here https://ocr-d.github.io/mets#media-type-for-page-xml.

Where would you prefer to find this information? Would it make more sense in https://ocr-d.github.io/page?

@chris1010010 Is the media type part of the PAGE specs themselves?

**Comment by finkf** [comment]
Hum. I have missed this. Thanks. I looked for it in the PAGE section.

**Comment by chris1010010** [comment]
At the moment the media type is only mentioned as "proposed type" at the bottom of the [PAGE GitHub page](https://github.com/PRImA-Research-Lab/PAGE-XML)

**Comment by finkf** [comment]
That's exactly where I found it :smile: 
Maybe just include a link in the PAGE section to the according mime-type in the METS section
