### ISSUE TITLE
CLI: Specifying multiple input/output groups

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#68]
Specs [say](https://ocr-d.github.io/cli#-i---input-file-grp-grp)

> `-I, --input-file-grp GRP`
> File group(s) used as input.

but not how multiple groups are to be given, right?

The most straightforward convention would be to use comma, as for `--group-id` and as implemented in [cis-ocrd-align](https://github.com/cisocrgroup/cis-ocrd-py).

**Comment by VolkerHartmann** [comment]
I know this convention to define multiple values:
Alternative 1: -I firstGroup, secondGroup, ...
Alternative 2: -I firstGroup -I secondGroup -I ...

**Comment by kba** [comment]
Sure, we use the first convention for output file fields (`ocrd workspace find -k url -k local_filename`) but the second convention seems to be established already.

Also, the first convention would force us to use a list internally everywhere which will break a lot of code or force us to remove a lot of convenience functions. Which at this point might actually not be that bad, technical-debt-wise.
