### ISSUE TITLE
transform the METSspec to METS Profile

### ISSUE THREAD

**Issue by tboenig** [OCR-D/spec#75]
I think it would be better that the METS specification is offered in a so-called METS Profile. 
A part of this Profile can already be found at: https://github.com/OCR-D/core/issues/147 . 
More information about the METS Profile and its format: 
  https://www.loc.gov/standards/mets/mets-profiles.html

**Comment by kba** [comment]
Sure, that would be very useful to include in specs. Although from what I've seen, these profiles are not as such machine-actionable. Could we express such rules with XSD/schematron?

**Comment by tboenig** [comment]
'machine-actionable' the idea is not so new, see : Machine Actionable METS 
Profiles (https://old.diglib.org/forums/spring2005/presentations/keith-2005-04.pdf)

**Comment by kba** [comment]
If it's about documenting our use and conventions how we use METS, the format seems not so important to me. Can't we continue the [markdown document](https://github.com/OCR-D/spec/blob/master/mets.md)?

Are there existing, reusable tools for METS profile validation with XML technologies, preferrably actively developed? The presentation has the right ideas for the time but 13 years have passed. How do metadata aggregators like europeana, dnb handle METS validation today?

Currently we're using [python to express the rules of our "profile"](https://github.com/OCR-D/core/blob/master/ocrd/validator/workspace_validator.py)

**Comment by wrznr** [comment]
@kba Yes, let us continue the markdown document; in particular after our projected discussion with @tboenig and Maria Federbusch. A digest will then be offered here.

**Comment by wrznr** [comment]
@tboenig @kba Has this idea being dropped as a result of your meeting?

**Comment by kba** [comment]
Yes, that idea is tabled for now. We will revisit this in January though because there might be METS schematron rules we could build upon that might be released end of the year (@maria-federbusch).

**Comment by cneud** [comment]
+1 for schematron rules

**Comment by wrznr** [comment]
Now, this issue is `Done` and not `Postponed`. How can we ensure its "revisitation"?
