### ISSUE TITLE
Convention for translating structured PAGE data to local mets:structMap

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#80]
How to map PAGE description to hierarchy level to create a level of contents?

How to handle pre-existing logical structmaps.

**Comment by wrznr** [comment]
Very much related to https://github.com/OCR-D/spec/issues/40

**Comment by kba** [comment]
The original idea is not feasible: MP will have to modify METS directly to create the TOC as logicalMap.

Still open: What to do if logicalMap is already there? Allowed in METS but tools like DFG-Viewer will only use the first logicmMap for TOC.

**Comment by wrznr** [comment]
I think that, at least for now, we should not bother ourselves with pre-existing structural annotations. That's a very complex topic since we are depending on the MPs treatment/processing of this information.

Btw. I am planning to support PAGE XML in https://github.com/deutschestextarchiv/tocrify

**Comment by VolkerHartmann** [comment]
The TOC is generated at the very beginning by the layout analysis, right? If there are several modules for this task, several TOCs have to be supported as well. In this case we have to link the TOC with the algorithm used, in case of parallel processing the chronological index might not be helpful. For the workflow it would be easier to save the results in a separate file as output. Are there modules based on these results? 
If this is the case, the results must be integrated into the METS file and provided with an index.

**Comment by VolkerHartmann** [comment]
Ahrg, I want to close my comment not the issue!

**Comment by kba** [comment]
> The TOC is generated at the very beginning by the layout analysis, right?

TOC is the result of document analysis, after recognition and post-processing.

> If there are several modules for this task, several TOCs have to be supported as well.

Potentially yes, but realistically: probably not.

> For the workflow it would be easier to save the results in a separate file as output. Are there modules based on these results?
If this is the case, the results must be integrated into the METS file and provided with an index.

I agree that conceptually, it would be easier to use the same mechanism as for all other steps (i.e. create a new file group `OCR-D-TOC` with files linking to individual METS files with only the logical structmap).

As I think about it, since @wrznr has started on an API that does exactly this and nothing else for tocrify, this could actually work. Then it would be only a matter of selecting one of those, possibly-many-but-realistically-single, METS file and adding the logical structMap to the original METS. This would also make it easier to spot exactly which parts of the METS were created by OCR-D processes and handle conflicts.

@cneud Thoughts?
