### ISSUE TITLE
METS: Mapping by page must be by physical structmap

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#81]
Currenly, we use the `GROUPID` of files to group different manifestations of the same file.

The more correct (and wider used) way is to create `mets:div` for every page in a `mets:structMap[TYPE="physical"]` and list `mets:ftpr` to all representations.

@tboenig @maria-federbusch Did I get that right?

**Comment by wrznr** [comment]
@tboenig Push.

**Comment by maria-federbusch** [comment]
You are right. The described way via mets:structMap[TYPE="physical"] is more correct.
