### ISSUE TITLE
Create a specification for necessary/relevant metadata for the GT repo

### ISSUE THREAD

**Issue by wrznr** [OCR-D/spec#85]
@VolkerHartmann wrote:
```
Input für das GT-Repo: Welche Metadaten sind für das GT-Repo wichtig?
(Es geht hier nicht um alle vorhandenen Metadaten, die stehen ja schon
in METS oder PAGE oder zukünftig ALTO?, sondern um die Metadaten,
die für die MPs interessant sind um die für sie wichtigen GT-Daten herauszufiltern.
Z.B. nur Titelseiten, bestimmte Sprachen, bestimmte Schriftarten, ...) Dafür
würde ich dann direkt Filter ins Repo einbauen, damit man die einfach finden und
dann auch entsprechend herunterladen kann. Dann muss ich wissen ob es auch
seitenbasierte Metadaten gibt oder ob alle Metadaten nur auf Dokument/Werk-
Ebene angesiedelt sind. Hilfreich wäre ein Beispieldatensatz in dem alle
Metadaten 'angestrichen' sind. Alternativ eine Liste mit den Metadaten und
X-Path wo ich sie finde.
```

**Comment by tboenig** [comment]
We are working on an implementation. This will be metadata concerning the Ground-Truth object itself (e.g. bibliographic information, physical state...) as well as metadata concerning the single page (page file).

I think the following information from the page file would be important:

```
<Metadata>
        <Creator></Creator>
<Created>2016-09-21T16:46:22.664+02:00</Created>
<LastChange>2017-01-04T09:59:59.013+01:00</LastChange>
        <Comments>
                Measurement unit: pixel
                PrimaryLanguage: German
                Language: GermanStandard
                Producer: ABBYY FineReader Engine 11</Comments>
    </Metadata>
```

In addition:
*  the used schema:
xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15/pagecontent.xsd"
  **XPATH:** /PcGts/@*[namespace-uri()='http://www.w3.org/2001/XMLSchema-instance' und local-name()='schemaLocation']]
*  the namespace of the schemas: 
xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15".
    **XPATH:** /PcGts/@xmlns
*  the used Font or Fonts: 
TextStyle @fontFamily=.....
   **XPATH:** //TextStyle/@fontFamily

**Comment by wrznr** [comment]
@VolkerHartmann @tboenig Has this issue been resolved to the satisfaction of both sides?

**Comment by kba** [comment]
https://docs.google.com/document/d/1lqpNV24xLtzK0S0qIJszGqUWFjV58XhEkmHUZ61CmbY/edit

**Comment by cneud** [comment]
Unsure of what's blocking this, I've had another look at the google doc and left some comments there.

**Comment by EEngl52** [comment]
@tboenig I guess this issue can be closed?

**Comment by kba** [comment]
Yes.
