### ISSUE TITLE
Group fileGrp by page instead of type

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/spec#9]
fileGrp IMAGE enthält alle Bilder von mind. einer Seite?
Man muss ja auf jeden Fall unterscheiden zwischen Originalbild und dem optimierten Bild.
Ich würde vielleicht eher die fileGrp so strukturieren, dass eine fileGrp alle Bilder einer Seite enthält.
1. Originalbild
2. optimiertes Bild
3 PAGE vom Originalbild
4. PAGE vom optimierten Bild
5 Für die Module evtl. noch weitere PAGE Dateien. z.B. Nachkorrektur

Alternativ wäre auch möglich beides in METS zu hinterlegen:
1. Nach (Datei-)typ (IMAGE, PAGE, ALTO, METS,...)

**Comment by cneud** [comment]
Die Idee wäre es, für die unterschiedlichen Prozessschritte eine "USE" in der fileGrp festzulegen wie z.B.:

<mets:fileGrp USE | Type of use for OCR-D
-- | --
<mets:fileGrp USE=”OCR-D-IMG”> | The unmanipulated source images
<mets:fileGrp USE=”OCR-D-IMG-BIN”> | Black-and-White images
<mets:fileGrp USE=”OCR-D-IMG-CROP”> | Cropped images
<mets:fileGrp USE=”OCR-D-IMG-DESKEW”> | Deskewed images
<mets:fileGrp USE=”OCR-D-IMG-DESPECK”> | Despeckled images
<mets:fileGrp USE=”OCR-D-IMG-DEWARP”> | Dewarped images
<mets:fileGrp USE=”OCR-D-SEG-PAGE”> | Page segmentation
<mets:fileGrp USE=”OCR-D-SEG-BLOCK”> | Block segmentation
<mets:fileGrp USE=”OCR-D-SEG-LINE”> | Line segmentation
<mets:fileGrp USE=”OCR-D-OCR-TESS”> | Tesseract OCR
<mets:fileGrp USE=”OCR-D-OCR-ANY”> | AnyOCR
<mets:fileGrp USE=”OCR-D-COR-CIS”> | CIS post-correction
<mets:fileGrp USE=”OCR-D-COR-ASV”> | ASV post-correction

**Comment by cneud** [comment]
Das hat auch den Vorteil dass in einer fileGrp sowohl seitenbasierte (PAGE, ALTO) als auch dokumentenbasierte (TEI etc.) Gruppen hinterlegt werden können, je nachdem wie es der Anwendungsfall benötigt (bspw. Nachkorrektur erfolgt auf Dokumentebene).

**Comment by kba** [comment]
`GROUPID` auf `mets:file` nutzen, um Dateien in den einzelnen Schritten auf die Ursprungsbilder abzubilden.

**Comment by cneud** [comment]
Fixed by 2e94a204ff35eb10275ec8bb575ba086b83817ca
