### ISSUE TITLE
How to undo OCR-D changes in METS

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#90]
Assume we need to reverse the changes to a METS file made by the tools within OCR-D. For example when reprocessing the same file, it would be useful (or event essential) not to duplicate all the agents and file groups and so on.

We could go through provenance tracking of workflow engine and basically reverse-patch METS with diffs in reverse chronological order.

Another approach would be to delete all file groups with `starts-with(@USE, "OCR-D")`, all agents with `starts-with(mets:name/text(), "ocrd")` ...

**Comment by bertsky** [comment]
This would also be very useful in the development phase. Processors will grow together, so being able to track changes in output or dependent input of one's test workspaces would help.

I am more inclined towards some `git revert` behaviour in the workflow engine rather than heuristic erasures or overwrites that are not traceable afterwards.

**Comment by kba** [comment]
I would also prefer a provenance-based behavior but since provenance is on the workflow level and an initial implementation still a few weeks away (@VolkerHartmann correct me if I'm wrong) I'm currently favoring a simple backup solution.

Whenever `workspace.save_mets` is called and backup behavior isn't explicitly disabled:

  * make sure a folder `.backup` exists
  * save current state of the METS file as `mets.xml.$(date '+%s')`

Have a subcommand `backups` on `ocrd workspace`:

```sh
ocrd workspace backup add -m mets.xml
> mkdir -p `.backup`
> Saving mets as `.backup/mets.xml.1540458596`

ocrd workspace backup add -m mets.xml
> Noting changed since `.backup/mets.xml.1540458596`

ocrd workspace backup list
> 1540458596 [Thu Oct 25 11:13:12 CEST 2018] OcrdMets[fileGrps=['OCR-D-IMG', 'OCR-D-IMG-DESKEW', 'OCR-D-IMG-DESPECK', 'OCR-D-IMG-DEWARP', 'OCR-D-IMG-CROP', 'OCR-D-IMG-BIN', 'OCR-D-SEG-PAGE', 'OCR-D-SEG-BLOCK', 'OCR-D-SEG-LINE', 'OCR-D-SEG-CLASS', 'OCR-D-SEG-DOC', 'OCR-D-OCR-TESS', 'OCR-D-OCR-ANY', 'OCR-D-COR-CIS', 'OCR-D-COR-ASV', 'OCR-D-GT-PAGE', 'OCR-D-GT-ALTO'] 41234 bytes

ocrd workspace backup undo
# shortcut for
# ocrd workspace backup restore 1540458596
> Overwrite mets.xml with `.backup/mets.xml.1540458596`? <Y/N>
```

@cneud

**Comment by bertsky** [comment]
Will that also delete files (from `mets:file ID`) and directories (from `mets:fileGrp USE`) introduced since the last backup? If not, will they be overwritten when repeating the step (by `workspace.add_file()` IINM)?

Another point: isn't the CLI supposed to work non-interactively? (Or is this a natural exception?)

**Comment by kba** [comment]
> Will that also delete files

No, at least not by default, since the files aren't backed up and there is always potential for catastrophic misjudged heuristics.  I have lots of ideas (like a diff summary which file groups were introduced by what agent etc.) but that should really be solved competetenly and thoroughly on the workspace level. This proposal is purely for development.

> If not, will they be overwritten when repeating the step (by workspace.add_file() IINM)?

`workspace.mets.add_file`, yes files will be overwritten.

> Another point: isn't the CLI supposed to work non-interactively? (Or is this a natural exception?)

This is the exception and that prompt was more to illustrate what is about to happen. But it's probably a good idea as a safeguard, disablable with a flag.

**Comment by bertsky** [comment]
That's all very convincing.

So is this issue still about the (production-oriented, probably workflow engine-implemented) specification, or rather about a development feature of `core`?

**Comment by kba** [comment]
Initially, I thought we could specify an algorithm for undoing changes. But since such a heuristics are brittle and we don't have specification on provenance yet to latch onto: the backup-based (pragmatic, development-oriented) solution. Should be in [OCR-D/core](https:/github.com/core) but cannot move issues across repos on GitHub.

**Comment by kba** [comment]
#204 merged
