### ISSUE TITLE
Make source code of GT guidelines public

### ISSUE THREAD

**Issue by wrznr** [OCR-D/spec#93]
At the moment, the GT guidelines have a kind of life of their own. It would be great if their sources could be included into the spec repository as another specification (which then could be reviewed and amended by 3rd parties).

**Comment by cneud** [comment]
IMHO we should provide the Transcription Guidelines via a separate - though public - repository under the @OCR-D hood. I fully agree that we should integrate these more with the [spec](https://github.com/OCR-D/spec) but would like to keep the code separate. 

Last but not least, this would also help with the envisioned translation of the guidelines.

**Comment by kba** [comment]
https://github.com/OCR-D/gt-guidelines
